### ISSUE TITLE
Git Workflow

### ISSUE THREAD

**Issue by AyudantesTecnicas** [TP0602-08/grupo-08#1]
Definir cual va a ser su workflow en Git. Pueden dejarlo especificado en una página de la Wiki.

https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow
http://nvie.com/posts/a-successful-git-branching-model/

**Comment by bliberini** [comment]
Se decide utilizar centralized workflow: https://www.atlassian.com/git/tutorials/comparing-workflows/centralized-workflow
